# Generated by Django 3.0.4 on 2020-03-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20200330_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dane',
            name='opis',
        ),
    ]
